### ISSUE TITLE
Issue with the FORGE_URL ENV variable

### ISSUE THREAD

**Issue by cmoulliard** [obsidian-toaster/generator-frontend#11]
The FORGE_URL is well defined to access the backend 

![screenshot 2016-12-01 12 25 52](https://cloud.githubusercontent.com/assets/463790/20792789/0ad0ec6a-b7c4-11e6-86ce-e013e483e859.png)

but an error is reported within the Web console 

![screenshot 2016-12-01 12 26 54](https://cloud.githubusercontent.com/assets/463790/20792809/1f91924e-b7c4-11e6-8540-89fd1836a594.png)

I suspect that the code doesn't use the ENV variable.

**Comment by edewit** [comment]
fixed in 4203dcd
