### ISSUE TITLE
Display error message when back-end is down

### ISSUE THREAD

**Issue by gastaldi** [obsidian-toaster/generator-frontend#16]
It would be nice if we could display an error message instead of presenting: The wizard is loading the initial screen... indefinitely

**Comment by gastaldi** [comment]
The console displays:

    "NetworkError: 404 Not Found - http://front-generator-obsidian.1ec1.dev-preview-int.openshiftapps.com/wizard/obsidian-new-project"

**Comment by edewit** [comment]
fixed ae3924167422576ab89ca58adedebb4a19968f6d
