### ISSUE TITLE
Next button shows outdated info from previous navigation

### ISSUE THREAD

**Issue by gastaldi** [obsidian-toaster/generator-frontend#18]
Steps to reproduce:

- Click "A starter" button
- select Vert.x and click Next
- Click back *FROM THE BROWSER*
- select Spring Boot and click next

The vert.x dependencies are shown. It should have displayed the spring boot deps instead

**Comment by edewit** [comment]
fixed in e248f590b520fee275dea7ae30fbe0bb891278ff
