### ISSUE TITLE
Cannot select more than one option in multiple select boxes

### ISSUE THREAD

**Issue by gastaldi** [obsidian-toaster/generator-frontend#2]
Whenever I choose more than an option in a multiple select box, only one item gets selected 
Steps to Reproduce:

- Choose Wildfly Swarm Microservice project type
- Click Next twice
-- You should be presented with a multiple select box select
- Select more than one option
- Click anywhere in the page to invoke the field's onchange
-- The select box only selects one option

**Comment by edewit** [comment]
done, was due to adding the 'multi select' attribute dynamically
