### ISSUE TITLE
UI text, I18N, and acessibility review

### ISSUE THREAD

**Issue by ColinHWalters** [obsidian-toaster/generator-frontend#25]
Comments at:  https://docs.engineering.redhat.com/display/~cwalters/Obsidian+Project+Wizard+Review

As always, there are suggestions only - there is nothing earth-shatteringly wrong with the UI as it stands.

Please let me know if you would like these suggestions presented in any other format or coding.

**Comment by gastaldi** [comment]
@ColinHWalters I believe some of the comments described in the document were fixed already in the master branch. Would it be possible to create separate issues for each comment in the document in here? 
Unfortunately the Openshift instance does not have the latest version, so If you could manage to run the frontend/backend locally it would be nice. If not, wait until we update http://front-generator-obsidian-snapshot.e8ca.engint.openshiftapps.com and I'll let you know.

**Comment by ColinHWalters** [comment]
Hi George,

How long before you update on openshiftapps?

Also, is creating JIRA issues an option instewad of git issues?      (That
way, I can group related comments (such as text string suggestions) into a
smaller number of issues and have JIRA reference/report on the doc
confluence page.)

Regards,

Colin





*Colin Howell Walters* | CCS Technical Writer, Remote NH.
cwalters@redhat.com; IRC: CHwalters
Mobile: 603-930-9893 (New Hampshire, USA)

**Comment by gastaldi** [comment]
Hi,

I'd prefer to have them on Github. The OBST JIRA is more focused on productization.

I believe you could group related comments into a single github issue as well, as those would be trivial to fix.

**Comment by gastaldi** [comment]
The latest snapshot is now deployed on http://generator-frontend-obsidian.dev.rdu2c.fabric8.io/wizard

Use that URL from now on, the other one will be discontinuated

**Comment by gastaldi** [comment]
The official URL is now http://start.prod-preview.openshift.io/wizard, please disregard the previous one

**Comment by ColinHWalters** [comment]
1. In the latest iteration for the generator, I'm not sure I understand the purpose of the 1 -> 2  progress bar for quickstarts, and the fact that it is "clickable but a no-op" is distracting.

2. We lost the "restart" button form the final screen, and I felt that was useful.  Clicking the placeholder icon to get back to the home page is non-intuitive, and we should not rely on browser back buttons for application navigation. 

3. The Back and Next buttons are still non-functional.

4.  I see some strange behavior when editing the name fields such as **demo**.  I type chars but they do not appear and the cursor jumps back one char.  It is very difficult to catch on a screen recorder.

**Comment by gastaldi** [comment]
Closing this as it is being handled by Jessica
