### ISSUE TITLE
Text fields lose focus

### ISSUE THREAD

**Issue by btison** [obsidian-toaster/generator-frontend#26]
In the frontend, whenever you position the mouse in a text field and start typing, the focus is lost after a second or so, forcing you to click again in the text box to continue typing. This happens in Chrome as well on Firefox (on Fedora 24).

To reproduce:
1. On the frontend start screen, click the 'using a quickstart' button.
2. On the next screen, click on the 'Project name' field
3. Type a couple of characters, then stop typing
4. The focus on the field is lost after ~1 sec

**Comment by gastaldi** [comment]
Hi @btison,

This is already fixed in the master branch. Can you give it a try running it locally? Not sure if the Openshift deployment is updated

**Comment by btison** [comment]
@gastaldi

Just verified on the master branch and the issue is indeed fixed. Closing the issue.

**Comment by gastaldi** [comment]
Thank you!
