### ISSUE TITLE
Filter the project types to display the containers

### ISSUE THREAD

**Issue by cmoulliard** [obsidian-toaster/generator-frontend#3]
This list 
<img width="823" alt="screenshot 2016-11-19 19 37 33" src="https://cloud.githubusercontent.com/assets/463790/20457641/c1e69276-ae8f-11e6-9e2f-905f91a35e2f.png"> displays the containers & types of project that we could use (jar, war, EAR).

I would like to suggest to dissociate the packaging type (jar, ear, war) from the container that we will include within zip file generated.

Field -> Container type : Eclipse Vert.x, WilfFly Swarm, Spring Boot
Field -> Packaging Type : jar, war, ear (=> this list is related to the container type chosen)

**Comment by gastaldi** [comment]
This needs to be done in the obsidian addon. The front-end just renders what's specified by the backend and the addon

**Comment by gastaldi** [comment]
As for the packaging type I am not 100% sure if this is an important choice when it comes to generating a sample project, do I'd recommend to avoid it and provide some instructions on how to execute it instead.
