### ISSUE TITLE
Breadcrumbs are clickable but they navigate to the wrong screen

### ISSUE THREAD

**Issue by gastaldi** [obsidian-toaster/generator-frontend#30]
1. Choose " Begin by selecting a runtime project framework (Eclipse Vert.x, WildFly Swarm, or Spring Boot)"
2. Select "WildFly Swarm"
3. Do not click next, click on #2 - WildFly Swarm: Setup in the upper section of the page
4. Spring Boot: Setup is presented instead

My guess is this is caused because it loses state when clicking on those steps.

**Comment by gastaldi** [comment]
Tested on http://start.prod-preview.openshift.io

**Comment by edewit** [comment]
fixed in 2eebccc080847801de945dd4612e57d8096e26e0
