### ISSUE TITLE
Use the project name to generate the zipped file name

### ISSUE THREAD

**Issue by cmoulliard** [obsidian-toaster/generator-frontend#8]
I think that we don't use the project-name as the name to create the zipped file name as the name of the zip is always called -> demo.zip

Example : project name = demo-vertx
Result : demo.zip

**Comment by edewit** [comment]
This is a [todo/issue](https://github.com/obsidian-toaster/generator-backend/blob/master/src/main/java/io/obsidian/generator/rest/ObsidianResource.java#L169) for the backend

**Comment by gastaldi** [comment]
The front-end is returning `execute` as the ZIP file name. Reopening issue

**Comment by gastaldi** [comment]
Apparently this is fixed. Reopen if the problem persists
