### ISSUE TITLE
Is there a reason why there is no field to define the version

### ISSUE THREAD

**Issue by cmoulliard** [obsidian-toaster/generator-frontend#9]
Is there a reason why there is not field to specify the version of the project to be generated ?

![screenshot 2016-11-28 19 25 38](https://cloud.githubusercontent.com/assets/463790/20680715/79c140b4-b5a0-11e6-96de-28fe8703437a.png)

**Comment by edewit** [comment]
@gastaldi can we add a version field?

**Comment by gastaldi** [comment]
Sure, no problem. This issue needs to be moved to obsidian-addon
